pipeline:
  build:
    image: node:8
    commands:
      - yarn
      - yarn test
  docker:
    image: plugins/docker
    when:
      branch:
        - master
      event: push
      status: success
    repo: abakus/event-reminder
    secrets: [ docker_username, docker_password ]
    tags:
      - ${DRONE_BRANCH}-${DRONE_COMMIT_SHA:0:7}
      - latest
    build_args:
      - RELEASE=${DRONE_BRANCH}-${DRONE_COMMIT_SHA:0:7}
