---
kind: pipeline
name: default
type: docker

trigger:
  event:
    exclude:
      - pull_request

steps:
  - name: build
    image: node:16
    commands:
      - yarn
      - yarn test

  - name: docker
    image: plugins/docker
    depends_on:
      - build
    when:
      event: [push]
      branch:
        - master
    settings:
      repo: abakus/event-reminder
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      tags:
        - ${DRONE_BRANCH}-${DRONE_COMMIT_SHA:0:7}
        - latest
      build_args:
        - RELEASE=${DRONE_BRANCH}-${DRONE_COMMIT_SHA:0:7}
